Upgrade notice to inform users of major change prior to 3.0.0 update
WordPress/performance pull request #1019
Opened 2024-02-28 08:38 UTC by mukeshpanchal27

## Summary

Fixes #655

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

2024-02-28 09:36 UTC, swissspidy commented on readme.txt
> +The WebP Uploads and Dominant Color Images modules will no longer be available starting with this release; instead, they'll be standalone plugins. If you're using these features, please migrate to th
They don't have to migrate before updating, since we have this whole migration logic in place.

So I'd just say something along the lines of:

```suggestion
Starting with this release, modules such as Dominant Color Images and WebP Uploads will be available as standalone plugins. After updating, you will be able to easily migrate to this new structure.
```

2024-02-28 17:29 UTC, westonruter commented on readme.txt
> +Starting with this release, modules such as Dominant Color Images and WebP Uploads will be available as standalone plugins. After updating, you will be able to easily migrate to this new structure.
```suggestion
Starting with this release, modules such as Dominant Color Images and WebP Uploads are only available as standalone plugins as opposed to bundled modules. After updating, you will be able to easily migrate to this new structure.
```

2024-02-28 18:00 UTC, felixarntz commented
Please take a look at https://github.com/WordPress/performance/issues/656#issuecomment-1969542264 where we can coordinate the next steps on how to proceed with this PR and #1011.

2024-02-28 18:01 UTC, felixarntz requested changes
@mukeshpanchal27 Thanks, this looks good to me, pending @westonruter's suggestion.

I'm putting a "request changes" similar to #1011, just until we decide how to proceed with this. See my above comment.

2024-03-02 02:54 UTC, felixarntz approved these changes
@mukeshpanchal27 LGTM, though we should probably merge #1011 first.

2024-03-06 02:59 UTC, westonruter approved these changes

2024-03-06 03:00 UTC, thelovekesh approved these changes

2024-03-06 03:56 UTC, merged