Reuse `WP_HTML_Processor::is_void()` now that WP 6.4 is minimum supported version
WordPress/performance pull request #1115
Opened 2024-04-06 20:39 UTC by westonruter

This removes a TODO to reuse `WP_HTML_Processor::is_void()` instead of replicating that functionality which was not available until WP 6.4. Now that 6.4 is the minimum-supported version, that method can be reused.

This could have been done previously in #1068 when the minimum version was bumped.

2024-04-08 15:46 UTC, felixarntz approved these changes
Good catch @westonruter!

2024-04-08 15:51 UTC, felixarntz requested changes
@westonruter Actually, it looks like https://github.com/WordPress/performance/actions/runs/8583685696/job/23573872147?pr=1115 has failures related to this change. Can you check?

2024-04-08 17:39 UTC, westonruter commented
@felixarntz Ah, this may have been an oversight in core that certain void tags were missed. I've opened Core-60961 to discuss that. In the meantime, probably better to let this PR sit.

2024-04-08 18:07 UTC, felixarntz commented
@westonruter SG. We should probably set the base to `trunk` then.

2024-04-08 18:20 UTC, westonruter commented
Oh, and actually `WP_HTML_Processor::is_void()` _was_ updated in 6.5 to include these deprecated void tags. So it's just that the version in 6.4 doesn't include them. So unless the change is backported to 6.4, this PR will have to wait until 6.5 is the minimum-supported version.

2024-07-09 23:16 UTC, westonruter commented
This was done in #1333.

2024-07-09 23:16 UTC, closed without merging