Update test class prefix
WordPress/performance pull request #1248
Opened 2024-05-26 13:15 UTC by sarthak-19

## Summary

Fixes #

## Relevant technical choices

2024-05-26 13:32 UTC, sarthak-19 commented
@thelovekesh Checks failing due to missing labels.

2024-05-28 16:58 UTC, westonruter requested changes

2024-05-28 16:58 UTC, westonruter commented on tests/plugins/optimization-detective/storage/rest-api-tests.php
Looks like this file needs to be renamed to `test-rest-api.php`

2024-05-28 16:58 UTC, westonruter commented on tests/plugins/optimization-detective/storage/data-tests.php
Rename to `test-data.php`?

2024-05-28 16:58 UTC, westonruter commented on tests/plugins/optimization-detective/storage/class-od-url-metrics-post-type-tests.php
Rename file to prefix with `test-`?

2024-05-28 16:58 UTC, westonruter commented on tests/plugins/optimization-detective/storage/class-od-storage-lock-tests.php
Rename file to prefix with `test-`?

2024-05-28 17:25 UTC, sarthak-19 commented on tests/plugins/optimization-detective/storage/rest-api-tests.php
Renamed the missing files

2024-05-28 17:28 UTC, westonruter commented on tests/plugins/performance-lab/includes/site-health/audit-enqueued-assets/testaudit-enqueued-assets.php
Should be `test-audit-enqueued-assets.php`

2024-05-28 17:30 UTC, westonruter commented
Let's also rename `tests/plugins/optimization-detective/uninstall-tests.php` to `test-uninstall.php`

2024-05-28 17:47 UTC, westonruter approved these changes

2024-05-28 17:49 UTC, merged