fix: Update WebP not Supported message
WordPress/performance pull request #1249
Opened 2024-05-26 17:06 UTC by the-hercules

Fixes (#715)
## Summary

Updated error message in the WordPress performance plugin regarding WebP image support. The message now informs users that WebP images require support from the web server's image processing libraries (Imagick or LibGD) and provides guidance on checking supported file formats.

2024-05-26 17:12 UTC, the-hercules commented
@thelovekesh Some checks are failing due to missing labels, can you add labels to this PR?

2024-05-27 07:27 UTC, mukeshpanchal27 requested changes
Thanks for the PR. The link should be clickable.

<img width="803" alt="Screenshot 2024-05-27 at 12 55 45 PM" src="https://github.com/WordPress/performance/assets/10103365/813b6a6d-3730-4f7b-a612-af07154513d8">

2024-05-30 19:47 UTC, joemcgill requested changes
Prior to merging these changes, I think we need to consider whether the updated text addresses the issue. See https://github.com/WordPress/performance/issues/715#issuecomment-2139932316.

2024-06-03 16:45 UTC, westonruter commented on plugins/performance-lab/includes/site-health/webp-support/helper.php
> +			__( 'WebP images are not currently supported by your web servers image processing libraries (Imagick or LibGD). This functionality is required to serve WebP images and improve website speed. Fortu
```suggestion
			__( 'WebP images are not currently supported by your web server's image processing libraries (Imagick or LibGD). This functionality is required to serve WebP images and improve website speed. Fortunately, these libraries have supported WebP for quite a while, so support is widely available. If your server does not support WebP, you will see an error message when you try to upload a WebP image. To check your supported file formats, go to Tools > Site Health > Info > Media Handling > Supported File Formats. For more information, visit <a href="https://learn.wordpress.org/lesson-plan/webp-images-in-wordpress/" target="_blank">WebP images in WordPress</a>.', 'performance-lab' )
```

2024-06-04 06:30 UTC, the-hercules commented on plugins/performance-lab/includes/site-health/webp-support/helper.php
> +			__( 'WebP images are not currently supported by your web servers image processing libraries (Imagick or LibGD). This functionality is required to serve WebP images and improve website speed. Fortu
Resolved

2024-06-04 16:44 UTC, westonruter commented
@the-hercules new suggested text from @adamsilverstein in https://github.com/WordPress/performance/issues/715#issuecomment-2147887299

2024-06-06 05:27 UTC, the-hercules commented
@westonruter does this message looks good ?

WebP support can only be enabled by your hosting provider. Please contact them to inquire about switching to a plan that supports WebP, or consider switching to a host that offers this feature. For more information about WebP image support for WordPress sites, please [Learn more](https://make.wordpress.org/hosting/2022/03/30/wordpress-hosting-and-webp-support/) here.

2024-06-06 16:10 UTC, westonruter commented
> For more information about WebP image support for WordPress sites, please [Learn more](https://make.wordpress.org/hosting/2022/03/30/wordpress-hosting-and-webp-support/) here.

I would phrase this rather as:

> [Learn more](https://make.wordpress.org/hosting/2022/03/30/wordpress-hosting-and-webp-support/) about WebP image support for WordPress sites.

I'll defer to @adamsilverstein for the ultimate wording.

2024-06-06 16:12 UTC, adamsilverstein commented
Looks good, including suggestion from @westonruter

2024-06-06 20:58 UTC, westonruter approved these changes
LGTM, with a possible improved word choice.

2024-06-06 20:58 UTC, westonruter commented on plugins/performance-lab/includes/site-health/webp-support/helper.php
> +			__( 'WebP support can only be enabled by your hosting provider. Please contact them to inquire about switching to a plan that supports WebP, or consider switching to a host that offers this featur
```suggestion
			__( 'WebP support can only be enabled by your hosting provider. Please contact them to inquire about switching to a plan that supports WebP, or consider switching to a host that offers this capability. <a href="https://make.wordpress.org/hosting/2022/03/30/wordpress-hosting-and-webp-support/" target="_blank">Learn more</a> about WebP image support for WordPress sites.', 'performance-lab' )
```

2024-06-07 04:02 UTC, westonruter approved these changes

2024-06-07 08:54 UTC, the-hercules commented
@mukeshpanchal27 @joemcgill Awaiting Review, I have made the suggested Changes.

2024-06-11 06:21 UTC, mukeshpanchal27 approved these changes

2024-06-12 06:44 UTC, the-hercules commented
Hey @joemcgill , Could you please review this PR.

2024-06-12 07:33 UTC, merged