Fix Modern Image Formats picture element support for selected image sizes
WordPress/performance pull request #1328
Opened 2024-07-02 12:50 UTC by imrraaj

## Description
This PR addresses an issue with the Modern Image Formats plugin's picture element support, where the generated markup did not account for the image sizes selected from the editor.
Fixes #1316 

## Problem
When using the Modern Image Formats plugin with picture element support enabled, the generated markup would load the full-size image instead of the selected image size (e.g., Thumbnail) and the <source> elements were missing for the selected image size.

## Solution
To fix this issue, the PR introduces the following changes:
- When the `$sizes` is false or `$image_srcset` is empty, then `$image_srcset` should be set to the modern image format version of the `$src`.
- `$image_srcset` then correctly generates the source tags and correct image size is set based on the value selected in the editor

## Testing
All the test are passing locally.

## Outcome

<img width="1604" alt="Screenshot 2024-07-02 at 6 15 07 PM" src="https://github.com/WordPress/performance/assets/71687258/ae291ec3-87d9-43a1-9946-20ceb8b603e7">

2024-07-02 19:09 UTC, westonruter commented
This PR should also include some test cases that demonstrate the original bug. Perhaps start there before adding the required fix, for some good ol' test-driven development.

2024-07-04 09:46 UTC, imrraaj commented
Based on my observations, the issue only affects JPG and JPEG images. Images with different MIME types are working as expected. The issue arises when the user has a JPG or JPEG image and the image size is set to `thumbnail`. When we select the thumbnail image size, it does not output the source tags which contain information about the `srcset` attribute, ultimately rendering the entire image as is with the given height and width. All the image sizes apart from thumbnail work fine (i.e., medium, large, full size).
I have written a test case just to demonstrate this. It will fail on the current state of the main branch, requiring the fix to be applied.

2024-07-05 19:08 UTC, westonruter commented on plugins/webp-uploads/tests/test-picture-element.php
> +		$this->assertStringContainsString( $jpg_source, $the_image );
Could you rather do a single `assertSame` assertion? By checking the entire string we can be extra confident it contains everything we expect.

2024-07-08 16:38 UTC, adamsilverstein commented
I verified the change worked as expected. I'm curious why thumbnail sizes in particular are handled this way. 

I checked with default WordPress without the plugin and noticed that no `srcset` is output when I select the thumbnail size, only the image tag:
![image](https://github.com/WordPress/performance/assets/2676022/f463e79d-1ddb-4033-aba7-6b3f0d3c2bc9)

If I select the medium size, I get a full srcset: 
![image](https://github.com/WordPress/performance/assets/2676022/7e651100-791a-491b-9d21-3e357fcee2e9)

This explains why the bug exists; for the picture element support we want to always have these srcsets so we can provide a fallback. I'm going to dig a little more to see if I can tell why core doesn't use `srcset` for thumbnails (or @joemcgill may know?) - probably because the images are small already so adding additional sizes doesn't make sense?

2024-07-08 18:38 UTC, westonruter commented
> I'm going to dig a little more to see if I can tell why core doesn't use `srcset` for thumbnails - probably because the images are small already so adding additional sizes doesn't make sense?

In looking at `wp_calculate_image_srcset()` I see it has these comments:

```
 	 * Loop through available images. Only use images that are resized
	 * versions of the same edit.
```
```
	 // If the image dimensions are within 1px of the expected size, use it.
```

Since thumbnails are square, as I understand they would only get a populated `srcset` if the original image was also a square.

I just tried uploading a square image and then inserting it with the thumbnail resolution, and the generated markup was:

```html
<img 
  decoding="async" 
  width="150" 
  height="150" 
  src="http://localhost:8888/wp-content/uploads/2024/07/pexels-mark-a-jenkins-373676419-21771035-150x150.jpg" 
  alt="" 
  class="not-transparent wp-image-43" 
  srcset="http://localhost:8888/wp-content/uploads/2024/07/pexels-mark-a-jenkins-373676419-21771035-150x150.jpg 150w, http://localhost:8888/wp-content/uploads/2024/07/pexels-mark-a-jenkins-373676419-21771035-300x300.jpg 300w, http://localhost:8888/wp-content/uploads/2024/07/pexels-mark-a-jenkins-373676419-21771035-1024x1024.jpg 1024w, http://localhost:8888/wp-content/uploads/2024/07/pexels-mark-a-jenkins-373676419-21771035-768x768.jpg 768w, http://localhost:8888/wp-content/uploads/2024/07/pexels-mark-a-jenkins-373676419-21771035-1536x1536.jpg 1536w, http://localhost:8888/wp-content/uploads/2024/07/pexels-mark-a-jenkins-373676419-21771035-2048x2048.jpg 2048w, http://localhost:8888/wp-content/uploads/2024/07/pexels-mark-a-jenkins-373676419-21771035-1568x1568.jpg 1568w" 
  sizes="(max-width: 150px) 100vw, 150px">
```

So here, even though the thumbnail was inserted, it _did_ get a fully-populated `srcset` because the other image sizes are also square.

2024-07-08 20:11 UTC, adamsilverstein commented
> it did get a fully-populated srcset because the other image sizes are also square.

this makes me wonder if the fix proposed here is correct. If a non-square image is uploaded, i suspect the fallbacks specified in the srcset entries will be distorted when displayed. Since no srcset is provided, we could instead use the 

maybe we could construct srcsets with the original image urls in each format (untested):

so for example



```
<picture class="wp-picture-407" style="display: contents;">
<img width="150" height="150" src="https://wpdev.localhost/wp-content/uploads/2024/07/cat-2-150x150.jpg" class="attachment-150x150 size-150x150" alt="">
</picture>
```
would become
```
<picture class="wp-picture-407" style="display: contents;">
<source type="image/avif" src="https://wpdev.localhost/wp-content/uploads/2024/07/cat-2-150x150.avif">
<source type="image/jpeg" src="https://wpdev.localhost/wp-content/uploads/2024/07/cat-2-150x150.jpg">
<img width="150" height="150" src="https://wpdev.localhost/wp-content/uploads/2024/07/cat-2-150x150.jpg" class="attachment-150x150 size-150x150" alt=""></picture>

note the `-150x150` suffix, including for the `img` tag. I'm not sure if the current PR uses that image correctly.
```

2024-07-08 20:11 UTC, adamsilverstein commented
> it did get a fully-populated srcset because the other image sizes are also square.

this makes me wonder if the fix proposed here is correct. If a non-square image is uploaded, i suspect the fallbacks specified in the srcset entries will be distorted when displayed. Since no srcset is provided, we could instead use the 

maybe we could construct srcsets with the original image urls in each format (untested):

so for example



```
<picture class="wp-picture-407" style="display: contents;">
<img width="150" height="150" src="https://wpdev.localhost/wp-content/uploads/2024/07/cat-2-150x150.jpg" class="attachment-150x150 size-150x150" alt="">
</picture>
```
would become
```
<picture class="wp-picture-407" style="display: contents;">
<source type="image/avif" src="https://wpdev.localhost/wp-content/uploads/2024/07/cat-2-150x150.avif">
<source type="image/jpeg" src="https://wpdev.localhost/wp-content/uploads/2024/07/cat-2-150x150.jpg">
<img width="150" height="150" src="https://wpdev.localhost/wp-content/uploads/2024/07/cat-2-150x150.jpg" class="attachment-150x150 size-150x150" alt=""></picture>

note the `-150x150` suffix, including for the `img` tag. I'm not sure if the current PR uses that image correctly.
```

2024-07-09 15:26 UTC, adamsilverstein requested changes
Needs some refinement to use only the cropped images (with matching sizes) - see comment thread

2024-07-10 21:37 UTC, westonruter commented
Bumping this to the next release.

2024-07-16 13:19 UTC, imrraaj commented
So I tried uploading a non-square image to test the code in the PR. When the thumbnail size is selected, it generates following HTML. 
```
<picture class="wp-picture-267" style="display: contents;">
<source type="image/webp" srcset="http://contrib.local/wp-content/uploads/2024/07/lake-8847415_1280-150x150.jpg" sizes="(max-width: 150px) 100vw, 150px">
<source type="image/jpeg" srcset="http://contrib.local/wp-content/uploads/2024/07/lake-8847415_1280-150x150.jpg" sizes="(max-width: 150px) 100vw, 150px">
<img width="150" height="150" src="http://contrib.local/wp-content/uploads/2024/07/lake-8847415_1280.jpg" class="attachment-150x150 size-150x150" alt="">
</picture>
```
So as per @adamsilverstein's suggestion along with source urls, the `img` tag url should also have `-150x150` suffix. Am I getting this right?

2024-07-29 09:34 UTC, closed without merging

2024-07-29 09:34 UTC, mukeshpanchal27 commented
@westonruter @adamsilverstein This has been solved in #1354 and merged in trunk. The IMG src check is added in #1408.

Closing this PR now.