Bump minimum required WordPress version to 6.6
WordPress/performance pull request #1683
Opened 2024-11-20 14:31 UTC by mukeshpanchal27

## Summary

Fixes #1682

2024-11-20 18:22 UTC, westonruter approved these changes

2024-11-20 18:26 UTC, felixarntz requested changes
Per the discussion in #1682, I don't see a good reason to bump the required WordPress version, even less so to 6.6 because the latest release is 6.7.

Let's continue discussion in the issue to determine what we want to do.

2024-12-03 06:08 UTC, mukeshpanchal27 commented
Per https://github.com/WordPress/performance/pull/1701#discussion_r1866206654 these one is unblocked and ready for review.

cc. @felixarntz @joemcgill

2024-12-03 16:35 UTC, joemcgill approved these changes
Based on @felixarntz response in https://github.com/WordPress/performance/pull/1701#discussion_r1866206654, this seems good now.

2024-12-03 16:53 UTC, felixarntz approved these changes

2024-12-03 17:23 UTC, merged