Module/database performance health check #522
WordPress/performance pull request #529
Opened 2022-09-13 20:32 UTC by OllieJones

## Summary

Implements #522 

## Relevant technical choices

Adds a module to the Performance Lab plugin per #475 

## Checklist

- [ ] PR has either `[Focus]` or `Infrastructure` label.
- [ ] PR has a `[Type]` label.
- [ ] PR has a milestone or the `no milestone` label.

2022-09-13 20:34 UTC, OllieJones commented
I don't have permission to add [Focus] Site Health  or [Module] Database Performance Health Check.

2022-09-14 04:41 UTC, mukeshpanchal27 commented
@OllieJones I have added the required labels. I have set `Feature` in the type label. Please let me know if it needs to be changed.

2022-09-15 12:51 UTC, mxbclang commented
Thanks @OllieJones and @mukeshpanchal27! I've updated these (added a milestone of 1.6.0 for now, though that can shift) and added to the Site Health project. @OllieJones Is this ready for review or are you still working through it?

2022-09-15 15:25 UTC, OllieJones commented
I'll fix the failiing unit test. Other than that, it's ready for review. Thanks in advance to reviewers.

2022-09-15 15:32 UTC, mxbclang commented
Thanks @OllieJones! @felixarntz @tillkruss Requesting your review here.

2022-09-27 15:15 UTC, OllieJones commented
@felixarntz @tillkruss Requesting your review here -- reminder.

2022-09-28 20:00 UTC, felixarntz requested changes
@OllieJones Thank you for the PR. I left some initial feedback. There are a couple of coding and documentation standards that need to be adjusted throughout the code.

Most importantly though, this PR is massive, and I think we would benefit from reducing it to a smaller subset of checks, then add other ones later. It is extremely challenging to review this much code in one PR and therefore even more challenging to get all parts across the finish line at once, so I would suggest we start small and then iterate. Even with only a few of these checks, the module already provides value which we could build upon.

I would suggest for now we keep only the following checks in here:
* `server_version_test()`
* `tables_format_test()`

These are the simpler ones, so an easier place to start. I would suggest you remove the other two and related logic for now and then open follow up PRs once this one is merged. Of course you will still be able to reuse the code for those later, maybe back up the branch somewhere else just in case.

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/assets/perflabdblists.css
> +}
We shouldn't adjust the styles from generic Site Health areas for this module. What is the reasoning to add this here? If there are specific elements added here which need styling, please use specific CSS selectors that don't affect general Site Health appearance.

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> + * @since 1.4.0
Please use throughout the PR:
```suggestion
 * @since n.e.x.t
```

There should be no specific `@since` tag in new code.

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> + *
No need for `@group`.
```suggestion
```

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> + * @since 1.4.0
`@package` should only be used on top of the file, not on classes. See above regarding `@group` and `@since`. Please update that throughout the PR.
```suggestion
 * Performance Lab database metrics class.
 *
 * @since n.e.x.t
```

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> +class PerflabDbMetrics {
Please follow the WP coding standards for class naming throughout (e.g. `Perflab_DB_Metrics`).

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> +		$this->util = PerflabDbUtilities::get_instance();
We shouldn't use singleton since it's an anti pattern and makes testing hard. We can either create a new instance here (if the class has state) or change the class to have static methods (if it's stateless).

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> +	/** First eligible db version, the advent of utfmb4 in WordPress databases.
Please adjust these docblocks throughout the PR. The description must always only start on the next line.
```suggestion
	/**
	 * First eligible db version, the advent of utfmb4 in WordPress databases.
```

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> +	public $first_compatible_db_version = 32814;
Please add `@since n.e.x.t` annotations to all member variables, and blank lines after.
```suggestion
	 * @since n.e.x.t
	 * @var int
	 */
	public $first_compatible_db_version = 32814;

```

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> +		}
Why `try catch` here? When would a `function_exists` ever fail?

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> +	 * @var bool false if we should error out on newer version.
Please leave out the description behind `@var` throughout the PR.
```suggestion
	 * @since n.e.x.t
	 * @var bool
```

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> +	 */
Please add `@since` to all methods, including constructor.
```suggestion
	/**
	 * Constructor.
	 *
	 * @since n.e.x.t
	 */
```

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbmetrics.php
> +		global $wp_db_version;
Globals should be declared on top of the method/function. Please also add `@global` docs to the method/function for which globals are used.

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbutilities.php
> +	}
Per how Site Health works, the badge label should always be `__( 'Performance', 'performance-lab' )` and the color should always be "blue". So I think you can remove these methods and instead incorporate these two values into the `result()` method, then make that public.

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbutilities.php
> +	private function result( $badge_label, $label, $description, $actions = '', $status = 'good', $color = 'blue' ) {
See my above comment, let's remove the `$badge_label` and `$color` parameters since it should always be the same for the Performance checks.

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbutilities.php
> +		 */
Please stick to the WP doc standards:
* The function/method description should start with a third-person verb.
* There should be no blank line between `@param` and `@return` docs.
* Descriptions and types should always be indented so that they show "in the same column". 
* Description should always start with a capital letter.
* There should be a return type description.

Please update all doc blocks like that throughout.
```suggestion
		/**
		 * Generates health-check result array.
		 *
		 * @since n.e.x.t
		 *
		 * @param string $badge_label Badge text next to accordion.
		 * @param string $label       Test label visible to user.
		 * @param string $description Test long description visible to user.
		 * @param string $actions     Actions to take to correct the problem, visible to user, default ''.
		 * @param string $status      'critical', 'recommended', 'good', default 'good'.
		 * @param string $color       A color specifier like 'blue', 'orange', 'red', default 'blue'.
		 * @return array The test result.
		 */
```

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbutilities.php
> +	const TERA = self::GIGA * self::KILO;
There are existing WordPress constants like `KB_IN_BYTES` which we should use instead of these ones.

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbtests.php
> +		$this->results[ $status ] [] = $result;
```suggestion
		$this->results[ $status ][] = $result;
```

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbtests.php
> +	 * @return void
Please omit any `@return void`.
```suggestion
	 * @param array $result Test result from individual test.
```

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/load.php
> +	return $pdp->add_all_database_performance_checks( $tests );
Some of the architecture here seems unnecessarily complex and sometimes unnecessarily abstracted. It makes sense to me to use classes here to a degree since the logic is more complex than in other checks, but for exactly the actual logic to amend `$tests` and maybe even the `alltests` callback method should rather be simple functions in this file instead of buried in class methods.

I would suggest to keep the classes only for the individual checks' logic but keep the entry point logic that executes the individual checks in functions here.

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbtests.php
> +	public function add_all_database_performance_checks( $tests ) {
See my other comment, I think this should be in the function in `load.php` instead.

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbtests.php
> +	public function alltests() {
See my other comments, I think this method should be a function in `load.php` instead. This way we keep the classes focused on purely the individual check logic and have those methods called from the functions, which cleans this up a little.

2022-09-28 20:00 UTC, felixarntz commented on modules/site-health/audit-database/class-perflabdbtests.php
> +		$this->add_result( $this->minimal_server_response_test() );
I think the `add_result` method and `$results` member variable in this class are not necessary and make the code more complex. The member isn't used outside of these two methods, so I think it should rather just be a variable within this method.

Instead of calling `add_result` for each check, you can simply iterate through an array of the checks and then have the same little logic you currently have in `add_result` in here.

2022-09-28 20:04 UTC, tillkruss commented
> Thanks @OllieJones! @felixarntz @tillkruss Requesting your review here.

I'm strapped for time this week. @OllieJones Can you make a video / screenshot tour to see what's actually going on?

2022-09-29 12:47 UTC, OllieJones commented on modules/site-health/audit-database/class-perflabdbtests.php
> +		$this->add_result( $this->minimal_server_response_test() );
Thanks, Felix. I'll hammer on these suggestions.

2022-10-12 16:32 UTC, felixarntz commented
This is still waiting for several updates, so punting this to the following release for now.

2022-12-14 22:30 UTC, felixarntz commented
There have been no updates here in a while, so this is not ready. Punting to 1.9.0 for now.

@OllieJones Is this one still on your radar?

2023-01-11 12:07 UTC, felixarntz commented
There haven't been any updates here for a few months now. I will remove the milestone for now, until this sees some traction again.

2024-04-30 12:27 UTC, closed without merging