Add dominant color styling before any existing inline style attributes
WordPress/performance pull request #716
Opened 2023-04-20 09:10 UTC by mukeshpanchal27

## Summary

To replicate the issue follow below steps:
- Go to Admin Panel then add new post
- Upload featured image for the post
- Add Cover block in which use "Use featured image" for image
- Select "FOCAL POINT PICKER"
- Check frontend.

**Before the patch:**
<img width="1345" alt="Screenshot 2023-04-20 at 2 37 17 PM" src="https://user-images.githubusercontent.com/10103365/233317502-0ea265e5-ddd5-4085-9635-ed5a3ebaf9e3.png">

**After the patch:**
<img width="1361" alt="Screenshot 2023-04-20 at 2 36 49 PM" src="https://user-images.githubusercontent.com/10103365/233317580-63e23bce-6b2c-4de1-910d-dca043486481.png">

Fixes #658

## Checklist

- [ ] PR has either `[Focus]` or `Infrastructure` label.
- [ ] PR has a `[Type]` label.
- [ ] PR has a milestone or the `no milestone` label.

2023-04-20 10:12 UTC, spacedmonkey commented on modules/images/dominant-color-images/hooks.php
>  		}
Maybe we should get rid of this..

2023-04-20 10:13 UTC, spacedmonkey commented on modules/images/dominant-color-images/hooks.php
> +		$style_attribute = $attr['style'];
```suggestion
		$style_attribute = empty( $attr['style'] ) ? '' : $attr['style'];
```

2023-04-20 10:13 UTC, spacedmonkey commented on modules/images/dominant-color-images/hooks.php
>  		}
```suggestion
```

2023-04-20 10:14 UTC, spacedmonkey commented on modules/images/dominant-color-images/hooks.php
> +		$attr['style']  .= '--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . ';' . $style_attribute;
```suggestion
		$attr['style']   = '--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . ';' . $style_attribute;
```

Would this not work?

2023-04-20 10:16 UTC, spacedmonkey requested changes
Some simple feedback, but otherwise, looking good.

2023-04-20 14:36 UTC, felixarntz reviewed
@mukeshpanchal27 Almost LGTM, except for what @spacedmonkey already pointed out.

2023-04-20 14:37 UTC, felixarntz commented
@mukeshpanchal27 Since this is a bug fix that has product side implications, we should add a milestone to the issue. `no milestone` should be reserved only for PRs which don't affect the end user-facing product (e.g. non-functional changes).

2023-04-20 16:55 UTC, joemcgill commented
Nothing additional from me. Thanks for adding a new unit test for this as well!

2023-04-21 05:16 UTC, mukeshpanchal27 commented
Thanks to all for the feedback. PR is ready for the second round of review.

2023-04-21 12:12 UTC, pbearne approved these changes

2023-04-21 16:34 UTC, felixarntz approved these changes
Thanks @mukeshpanchal27!

2023-04-21 16:37 UTC, spacedmonkey approved these changes

2023-04-21 16:37 UTC, merged