Issue templates for bug reports and feature requests
WordPress/performance pull request #88
Opened 2022-01-13 16:38 UTC by eugene-manuilov

Addresses #68

2022-01-13 16:51 UTC, mitogh requested changes
Missing some characters, other than that looks great.

2022-01-13 16:51 UTC, mitogh commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Browser [e.g. chrome, safari]
```suggestion
 - Browser: [e.g. chrome, safari]
```

2022-01-13 16:51 UTC, mitogh commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Plugin Version [e.g. 22]
```suggestion
 - Plugin Version: [e.g. 22]
```

2022-01-13 18:50 UTC, mitogh approved these changes

2022-01-14 19:08 UTC, jeffpaul commented
I would strongly recommend changing these to YML files to use the [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) and help force some of the issue content we're wanting/needing.  [Examples here](https://github.com/10up/simple-podcasting/tree/develop/.github/ISSUE_TEMPLATE).

2022-01-15 16:37 UTC, felixarntz commented
@jeffpaul IMO we can still merge this as a starting point (better than not having any), but I like your idea - would you mind to open an issue about using YML files instead so we can discuss there and iterate?

2022-01-17 10:00 UTC, JustinyAhin commented
> @jeffpaul IMO we can still merge this as a starting point (better than not having any), but I like your idea - would you mind to open an issue about using YML files instead so we can discuss there and iterate?

I can go ahead and create and issue and a draft PR @felixarntz

2022-01-28 10:41 UTC, felixarntz approved these changes

2022-01-28 10:41 UTC, merged

2022-01-28 10:41 UTC, felixarntz commented
@JustinyAhin Sounds great - could you follow up on this?