Add support for manually running the PHPUnit workflow.
WordPress/performance pull request #991
Opened 2024-02-15 19:40 UTC by joemcgill

## Summary

This merges #990 into the 2.9 branch.

2024-02-15 19:44 UTC, westonruter approved these changes

2024-02-16 16:03 UTC, thelovekesh approved these changes

2024-02-19 09:39 UTC, mukeshpanchal27 requested changes
Why do we need these changes in the `2.9.0` branch? It's not a blocker, and it's infrastructure-related, so it won't affect the plugin code or anything in the release. 🤔

I'm happy to approve it, but I just need to understand why. Since the changes are already in trunk, why do we need them in the release branch?

2024-02-19 23:48 UTC, joemcgill commented
> Why do we need these changes in the 2.9.0 branch?

We don't, actually. However, opening this PR allowed us to verify that PHPUnit was not failing in the 2.9.0 branch, by re-triggering the workflow. Going to close this as unnecessary.

2024-02-19 23:48 UTC, closed without merging