Remove repo specific Code of Conduct
WordPress/performance pull request #994
Opened 2024-02-16 02:28 UTC by desrosj

## Summary
This removes the repository specific `CODE_OF_CONDUCT.md` file in favor of the newly added version maintained as the organization's default within the WordPress/.github repository.

While this file will not be included in `git clone`s, it will be displayed on the repository's main page and anywhere else GitHub includes a Code of Conduct link.

This change enables more consistent messaging for the community code of conduct, and allows the file to be updated in one location for all repositories under the WordPress organization.

See https://github.com/WordPress/.github/pull/1.

2024-02-16 02:38 UTC, westonruter approved these changes

2024-02-19 03:49 UTC, mukeshpanchal27 requested changes
Thanks, @desrosj, for the PR!

One instance is missing here: https://github.com/WordPress/performance/blob/trunk/CONTRIBUTING.md?plain=1#L15

2024-02-20 13:34 UTC, desrosj commented
Thanks @mukeshpanchal27! I've gone and fixed that reference.

2024-02-21 03:37 UTC, mukeshpanchal27 approved these changes

2024-02-21 03:38 UTC, merged